### ISSUE TITLE
Extract prompt feature

### ISSUE THREAD

**Issue by s10400015** [yujiangpu20/PEL4VAD#6]
作者你好

我在執行 python token_extract.py --dataset 'ucf' 遇到錯誤如下

Traceback (most recent call last):
  File "token_extract.py", line 3, in <module>
    import clip
  File "/home/ee401-2/PEL4VAD-master/prompt_extract/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/home/ee401-2/PEL4VAD-master/prompt_extract/clip/clip.py", line 43
    def _download(url: str, root: str):
                     ^
SyntaxError: invalid syntax

想請問這要如何修改

**Comment by yujiangpu20** [comment]
请参考 https://github.com/openai/CLIP 配置CLIP模型所需运行环境
